services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusPlusAdapterPlugin\:
        resource: '../../*'
        exclude: '../../Form/Extension/*'

